[theme]
primaryColor = "#2196F3"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#212121"
font = "sans serif"

[server]
maxUploadSize = 10
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
